
name: BuildOnPR

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli -g
        sfdx --version
        sfdx plugins --core

    - name: Authenticate DevHub
      run: |
        echo "${SFDX_AUTH_URL}" > urlfile
        sfdx force:auth:sfdxurl:store -f urlfile -a devhub -d
      env:
        SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}

    - name: Create scratch org
      run: sfdx force:org:create -u ciorg -f config/project-scratch-def.json --durationdays 1 --setdefaultusername --json --loglevel fatal

    - name: Push source
      run: sfdx force:source:push -f

    - name: Run Apex test
      run: sfdx force:apex:test:run -c -r human

    - name: Delete scratch org
      if: ${{ always() }}
      run: sfdx force:org:delete -u ciorg -p
